export enum Permiso {
  COMPLETAR_REGISTRO = 'COMPLETAR_REGISTRO',
  USAR_FUNCIONALIDADES_PERSONALES = 'USAR_FUNCIONALIDADES_PERSONALES',
  CONSULTAR_ESTADISTICAS_AGREGADAS = 'CONSULTAR_ESTADISTICAS_AGREGADAS',
}
