-- Versiones independientes por combinación clínica. La coherencia de la
-- combinación y la unicidad del árbol publicado ya existen en la base.
CREATE UNIQUE INDEX uq_flujo_version_personalizada
  ON chat.flujo_conversacion (tipo_dependencia, tipo_craving, version)
  WHERE modalidad = 'PERSONALIZADA'::chat.modalidad_enum;

ALTER TABLE chat.flujo_conversacion
  ADD CONSTRAINT ck_flujo_version_positiva CHECK (version > 0);

CREATE TABLE chat.auditoria_arboles (
  id_auditoria BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_flujo UUID NOT NULL,
  id_actor UUID NOT NULL,
  accion VARCHAR(40) NOT NULL,
  id_objeto UUID,
  fecha_operacion TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_auditoria_arbol_flujo FOREIGN KEY (id_flujo)
    REFERENCES chat.flujo_conversacion (id_flujo) ON DELETE RESTRICT,
  CONSTRAINT fk_auditoria_arbol_actor FOREIGN KEY (id_actor)
    REFERENCES usuario.usuarios (id_usuario) ON DELETE RESTRICT,
  CONSTRAINT ck_auditoria_arbol_accion CHECK (accion IN (
    'CREAR_FLUJO', 'CLONAR_VERSION', 'CREAR_NODO', 'EDITAR_NODO',
    'CREAR_TRANSICION', 'EDITAR_TRANSICION', 'PUBLICAR', 'ARCHIVAR'
  ))
);

CREATE INDEX ix_auditoria_arbol_flujo_fecha
  ON chat.auditoria_arboles (id_flujo, fecha_operacion);

CREATE FUNCTION chat.fn_auditoria_arbol_inmutable() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'La auditoría del árbol conversacional es inmutable';
END;
$$;

CREATE TRIGGER trg_auditoria_arbol_inmutable
BEFORE UPDATE OR DELETE ON chat.auditoria_arboles
FOR EACH ROW EXECUTE FUNCTION chat.fn_auditoria_arbol_inmutable();
